### ISSUE TITLE
Update to use Google Code Style

### ISSUE THREAD

**Issue by trcox** [edgexfoundry/device-modbus#2]
Propagate code style changes from SDK to project.

**Comment by chadyoungdell** [comment]
I see the error below when trying to read from a modbus RTU device in EdgeX
Below is the error I see:

[2017-11-08 20:21:16.121] boot - 5  INFO [pool-10-thread-1] --- HeartBeat: This is the device-modbus device service.
[2017-11-08 20:23:32.530] boot - 5  INFO [http-nio-49991-exec-1] --- DeviceStore: Adding managed device:  livingroomthermostat
[2017-11-08 20:23:35.187] boot - 5  INFO [http-nio-49991-exec-1] --- ModbusHandler: Initialized Device: livingroomthermostat
[2017-11-08 20:25:09.634] boot - 5  INFO [Thread-8] --- ModbusDriver: ProcessCommand: get, addressable:Addressable [name=datanab thermo address, protocol=OTHER, address=/dev/ttyS0,19200,8,1,0, port=48089, path=, publisher=none, user=none, password=none, topic=none, toString()=BaseObject [id=5a036715e4b0c393da4d03dc, created=1510172437076, modified=1510172437076, origin=1471806386919]], attributes:102, value: null
[2017-11-08 20:25:09.669] boot - 5  INFO [Thread-8] --- ModbusConnection: Port:/dev/ttyS0
[2017-11-08 20:25:09.700] boot - 5  INFO [Thread-8] --- ModbusConnection: BaudRate:19200
[2017-11-08 20:25:09.718] boot - 5  INFO [Thread-8] --- ModbusConnection: Data Bits:8
[2017-11-08 20:25:09.744] boot - 5  INFO [Thread-8] --- ModbusConnection: Stop Bitse:1
[2017-11-08 20:25:09.776] boot - 5  INFO [Thread-8] --- ModbusConnection: Parity:0
[2017-11-08 20:25:10.399] boot - 5  INFO [Thread-8] --- ModbusDriver: Getting value
[2017-11-08 20:25:10.478] boot - 5  INFO [Thread-8] --- ModbusConnection: Holding Register:102
[2017-11-08 20:25:11.116] boot - 5  WARN [Thread-8] --- ModbusConnection: Cannot get the value:I/O exception - failed to read response for request [01 03 00 66 00 01] - Cannot read from serial port,count:1
[2017-11-08 20:25:11.124] boot - 5  INFO [Thread-8] --- ModbusConnection: Holding Register:102
[2017-11-08 20:25:11.740] boot - 5  WARN [Thread-8] --- ModbusConnection: Cannot get the value:I/O exception - failed to read response for request [01 03 00 66 00 01] - Cannot read from serial port,count:2
[2017-11-08 20:25:11.747] boot - 5  INFO [Thread-8] --- ModbusConnection: Holding Register:102
Exception in thread "Thread-8" org.edgexfoundry.exception.BadCommandRequestException: I/O exception - failed to read response for request [01 03 00 66 00 01] - Cannot read from serial port
at org.edgexfoundry.modbus.ModbusConnection.getValue(ModbusConnection.java:204)
at org.edgexfoundry.modbus.ModbusConnection.getValue(ModbusConnection.java:201)
at org.edgexfoundry.modbus.ModbusConnection.getValue(ModbusConnection.java:201)
at org.edgexfoundry.modbus.ModbusDriver.processCommand(ModbusDriver.java:82)
at org.edgexfoundry.modbus.ModbusDriver.process(ModbusDriver.java:69)
at org.edgexfoundry.handler.ModbusHandler.lambda$executeOperations$0(ModbusHandler.java:191)
at java.lang.Thread.run(Thread.java:748)

In trying to debug the issue I think it comes down to not being able to write to the correct "Modbus Slave ID". I came to this conclusion based on two pieces of info. (1) I do not see an option to specify the "Slave ID" and (2) the failure above "failed to read response for request [01 03 00 66 00 01]​". 
 
From the Modbus commands being sent to the device [01 03 00 66 00 01] this is what I see
01: The Slave Address (01 hex = address 01 )
03: The Function Code 3 (read Analog Output Holding Registers)
0066: The Data Address of the first register requested.
             ( 0066 hex = 102 , input 102 )
0001: The total number of registers requested. (read 1 register)  
 
Since I am trying to read the device on "Slave ID 254" and edgex is telling it to read "Slave ID 1", it make sense that it not able to read from the device.

**Comment by chadyoungdell** [comment]
The issue is related to the "req.setUnitID();" originally being set statically to "0". Using the patch created below - by Tyler Cox - the Modbus RTU device can now successfully be read. I will be editing the code and issuing a pull request later today.

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

diff --git a/src/main/java/org/edgexfoundry/modbus/ModbusConnection.java b/src/main/java/org/edgexfoundry/modbus/ModbusConnection.java
index 196b20d..b4a7883 100644
--- a/src/main/java/org/edgexfoundry/modbus/ModbusConnection.java
+++ b/src/main/java/org/edgexfoundry/modbus/ModbusConnection.java
@@ -145,7 +145,7 @@ public class ModbusConnection {
                if(connection instanceof TCPMasterConnection){
                        TCPMasterConnection con = (TCPMasterConnection)connection;
 
-                       req.setUnitID(0);
+                       req.setUnitID(Integer.valueOf(addressable.getPath()));
 
                        try
                        {
@@ -177,7 +177,7 @@ public class ModbusConnection {
                        }
                }
                else if(connection instanceof SerialConnection){
-                       req.setUnitID(1);
+                       req.setUnitID(Integer.valueOf(addressable.getPath()));
                        req.setHeadless();
                        SerialConnection con = (SerialConnection)connection;
                        try
